### PR TITLE
Added VolunteerForm

### PR DESCRIPTION
**Pull request by aachintya**
## Description

1. Added VolunteerForm and it's backend.
2. Ensured Aadhar Card are hashed before storing 
3. Added Form Validation to ensure inputs are given in correct format

## Related Issue

#4 

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Motivation and Context

It's a progress to make it a fully functional website. Now people can apply as volunteer.

## How Has This Been Tested?

Used console and networks in chrome developer tools to debug error

## Screenshots (if appropriate):

[Demo](https://drive.google.com/file/d/1KiBrChV03qxCdWcacSQUElXHF7XCalo_/view?usp=sharing
)
## Checklist:

- [x] I have registered myself at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
- [x] My code follows the code style of this project.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

### CODE REVIEW

**Comment by Codipk** [comment]
if u have hashed the adhar card then if I want to see  the adhar no ? can it be decrypt? @aachintya

**Comment by aachintya** [comment]
> if u have hashed the adhar card then if I want to see the adhar no ? can it be decrypt? @aachintya

currently no, cause i am hashing using SHA-256. it's a one way encryption
i can change that if you want

**Comment by Codipk** [comment]
Yess , so just save the adharno as it is , bcoz we want that adhar no to display in admin portal

**Comment by Codipk** [comment]
@aachintya have u made the changes?
If not let it be ....I'll see that

**Comment by aachintya** [comment]
ok i'll do it real quick

**Pull request merged**
